// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyqkccjhmxvwqnbsbywf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5cWtjY2pobXh2d3FuYnNieXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDIzMTEsImV4cCI6MjA2ODMxODMxMX0.kkMb7KXMkNVfWg2cY4tQYeWvZop3bV-m6qUTwY-1zlY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});